### ISSUE TITLE
'timeoutHandler' and 'doInput' are inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by BigSauce** [shogo4405/Logboard#3]
I'm getting the following compiler errors when pulling the latest release: **Logboard (1.1.7)**

![image](https://user-images.githubusercontent.com/1718470/44111299-0a35576e-9fd0-11e8-8449-c9010c64e393.png)
![image](https://user-images.githubusercontent.com/1718470/44111423-5ec41734-9fd0-11e8-8e98-8932cfb51611.png)
![image](https://user-images.githubusercontent.com/1718470/44111387-3f159ef8-9fd0-11e8-83be-cde2a12ca20c.png)

**Comment by shogo4405** [comment]
It seems you are using Swift3.x.
Please use Logboard 1.0.x.
